
services:
  - type: web
    name: erlc-language
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 1
