
services:
  - type: web
    name: erlc-language
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production npm run start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /health
